import Head from "next/head";

export default function Create(){
    return (
        <>
        <Head>
            <title>Donate Crypto</title>
            <meta charSet="utf-8" />
            <meta name="description" content="Generated by create next app"/>
            <meta name="viewport" content="width=device-width, initial-scale-1"/>
        </Head>
        <div className="container">
        <h1 className="display-5 fw-bold text-body-emphasis lh-1 mb-3">
            Donate Crypto
          </h1>
          <p>Fill in the required fields to create your campaing</p>
          <hr className="mb-4"/>
          <div className="col-6">
            
          </div>
        </div>
        </>
    )
}